### ISSUE TITLE
ValueError: Imaginary component

### ISSUE THREAD

**Issue by NiuWenjie** [mseitzer/pytorch-fid#13]
I am getting this error when computing FID between 2 datasets.
```
Traceback (most recent call last):
  File "fid_score.py", line 260, in <module>
    args.dims)
  File "fid_score.py", line 248, in calculate_fid_given_paths
    fid_value = calculate_frechet_distance(m1, s1, m2, s2)
  File "fid_score.py", line 184, in calculate_frechet_distance
    raise ValueError('Imaginary component {}'.format(m))
ValueError: Imaginary component 0.6888144870124462

```

**Comment by mseitzer** [comment]
I guess you did not use at least 2048 samples in one of your datasets.

See: https://github.com/bioinf-jku/TTUR/issues/4
