### ISSUE TITLE
ValueError: could not broadcast input array from shape (256,256,3) into shape (256,256)

### ISSUE THREAD

**Issue by Ha0Tang** [mseitzer/pytorch-fid#22]
12%|█████████▏                                                                   | 12/100 [00:03<00:25,  3.47it/s]
Traceback (most recent call last):
  File "fid_score.py", line 261, in <module>
    args.dims)
  File "fid_score.py", line 246, in calculate_fid_given_paths
    dims, cuda)
  File "fid_score.py", line 228, in _compute_statistics_of_path
    dims, cuda)
  File "fid_score.py", line 213, in calculate_activation_statistics
    act = get_activations(files, model, batch_size, dims, cuda, verbose)
  File "fid_score.py", line 111, in get_activations
    for f in files[start:end]])
ValueError: could not broadcast input array from shape (256,256,3) into shape (256,256)

**Comment by Ha0Tang** [comment]
Solved!

**Comment by herobd** [comment]
For someone else coming along, this is likely caused by images not being the same size.
