### ISSUE TITLE
"UnicodeDecodeError" during installation

### ISSUE THREAD

**Issue by kkunal1408** [mseitzer/pytorch-fid#49]
command: /usr/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jnses9_7/pytorch-fid/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jnses9_7/pytorch-fid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-v7ho1gid
         cwd: /tmp/pip-install-jnses9_7/pytorch-fid/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jnses9_7/pytorch-fid/setup.py", line 5, in <module>
        long_description = fh.read()
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by kkunal1408** [comment]
This error can be fixed by adding encoding information while reading README.md in setup.py.
change line: with open('README.md', 'r') as fh:
as : with open('README.md', 'r', encoding='utf-8') as fh:
