### ISSUE TITLE
Filed to install pytorch-fid

### ISSUE THREAD

**Issue by SeibertronSS** [mseitzer/pytorch-fid#71]
## Filed to install pytorch-fid
I got such an error message when installing pytorch-fid :
```
  Using cached https://files.pythonhosted.org/packages/93/54/49dc21a5ee774af0390813c3cf66af57af0a31ab22ba0c2ac02cdddeb755/pytorch-fid-0.2.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-8fyl64am/pytorch-fid/setup.py'"'"'; __file__='"'"'/tmp/pip-install-8fyl64am/pytorch-fid/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-8fyl64am/pytorch-fid/pip-egg-info
         cwd: /tmp/pip-install-8fyl64am/pytorch-fid/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-8fyl64am/pytorch-fid/setup.py", line 30, in <module>
        long_description=read('README.md'),
      File "/tmp/pip-install-8fyl64am/pytorch-fid/setup.py", line 9, in read
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 174: ordinal not in range(128)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
What should be done to fix this problem?

**Comment by mseitzer** [comment]
I can not reproduce this issue. Can you try to install `pytorch-fid` in a fresh virtual environment?

**Comment by SeibertronSS** [comment]
> 我无法重现此问题。您可以尝试在一个新的虚拟环境中安装吗？`pytorch-fid`

I will try this method . Thank you very much for your reply.
