### ISSUE TITLE
No module named pytorch_fid

### ISSUE THREAD

**Issue by cdinea** [mseitzer/pytorch-fid#92]
Hi!

I pip installed PyTorch-fid but when I run
`python -m pytorch_fid ~/fid/real_data ~/fid/synthetic_data`
I get 

`/usr/bin/python: No module named pytorch_fid`

And when running

`python3 -m pytorch_fid ~/fid/real_data ~/fid/synthetic_data`
```
Traceback (most recent call last):
  File "/usr/local/Modules/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Modules/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cdinea/.local/lib/python3.7/site-packages/pytorch_fid/__main__.py", line 1, in <module>
    import pytorch_fid.fid_score
  File "/home/cdinea/.local/lib/python3.7/site-packages/pytorch_fid/fid_score.py", line 40, in <module>
    import torchvision.transforms as TF
  File "/home/cdinea/.local/lib/python3.7/site-packages/torchvision/__init__.py", line 5, in <module>
    from torchvision import datasets, io, models, ops, transforms, utils
  File "/home/cdinea/.local/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
    from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
  File "/home/cdinea/.local/lib/python3.7/site-packages/torchvision/datasets/_optical_flow.py", line 12, in <module>
    from .utils import _read_pfm, verify_str_arg
  File "/home/cdinea/.local/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 1, in <module>
    import bz2
  File "/usr/local/Modules/lib/python3.7/bz2.py", line 19, in <module>
    from _bz2 import BZ2Compressor, BZ2Decompressor
ModuleNotFoundError: No module named '_bz2'
```

**Comment by zy-charon** [comment]
> 你好！
> 
> 我 pip 安装了 PyTorch-fid 但是当我运行时 `python -m pytorch_fid ~/fid/real_data ~/fid/synthetic_data` 我得到
> 
> `/usr/bin/python: No module named pytorch_fid`
> 
> 而在跑步的时候
> 
> `python3 -m pytorch_fid ~/fid/real_data ~/fid/synthetic_data`
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/Modules/lib/python3.7/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/local/Modules/lib/python3.7/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/home/cdinea/.local/lib/python3.7/site-packages/pytorch_fid/__main__.py", line 1, in <module>
>     import pytorch_fid.fid_score
>   File "/home/cdinea/.local/lib/python3.7/site-packages/pytorch_fid/fid_score.py", line 40, in <module>
>     import torchvision.transforms as TF
>   File "/home/cdinea/.local/lib/python3.7/site-packages/torchvision/__init__.py", line 5, in <module>
>     from torchvision import datasets, io, models, ops, transforms, utils
>   File "/home/cdinea/.local/lib/python3.7/site-packages/torchvision/datasets/__init__.py", line 1, in <module>
>     from ._optical_flow import FlyingChairs, FlyingThings3D, HD1K, KittiFlow, Sintel
>   File "/home/cdinea/.local/lib/python3.7/site-packages/torchvision/datasets/_optical_flow.py", line 12, in <module>
>     from .utils import _read_pfm, verify_str_arg
>   File "/home/cdinea/.local/lib/python3.7/site-packages/torchvision/datasets/utils.py", line 1, in <module>
>     import bz2
>   File "/usr/local/Modules/lib/python3.7/bz2.py", line 19, in <module>
>     from _bz2 import BZ2Compressor, BZ2Decompressor
> ModuleNotFoundError: No module named '_bz2'
> ```
Excuse me, did you solve it, I also encountered this problem：No module named pytorch-fid.

**Comment by zuzhal** [comment]
I have the same problem, any chance you have managed to solve it?
